# Git Setup Script for Django Project (PowerShell)
# This script helps add templates, static files, and other important files to git

Write-Host "🚀 Django Project Git Setup" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "📁 Checking directories..." -ForegroundColor Yellow

if (Test-Path "templates") {
    Write-Host "✅ templates/ directory found" -ForegroundColor Green
} else {
    Write-Host "❌ templates/ directory missing!" -ForegroundColor Red
}

if (Test-Path "static") {
    Write-Host "✅ static/ directory found" -ForegroundColor Green
} else {
    Write-Host "❌ static/ directory missing!" -ForegroundColor Red
}

if (Test-Path "staticfiles") {
    Write-Host "⚠️  staticfiles/ directory exists (will be ignored - it's generated)" -ForegroundColor Yellow
} else {
    Write-Host "ℹ️  staticfiles/ directory not found (normal - it's generated)" -ForegroundColor Blue
}

Write-Host ""
Write-Host "📋 Git operations..." -ForegroundColor Yellow

# Initialize git if not already done
if (-not (Test-Path ".git")) {
    Write-Host "🔄 Initializing git repository..." -ForegroundColor Cyan
    git init
} else {
    Write-Host "✅ Git repository already initialized" -ForegroundColor Green
}

# Add .gitignore first
Write-Host "🔄 Adding .gitignore..." -ForegroundColor Cyan
git add .gitignore

# Add all Django project files
Write-Host "🔄 Adding Django project files..." -ForegroundColor Cyan
git add manage.py
git add requirements.txt
git add runtime.txt
git add "*.md"

# Add app directories
Write-Host "🔄 Adding Django apps..." -ForegroundColor Cyan
git add accounts/
git add chat/
git add genai_project/

# Add templates and static files (source, not generated)
Write-Host "🔄 Adding templates..." -ForegroundColor Cyan
git add templates/

Write-Host "🔄 Adding static source files..." -ForegroundColor Cyan
git add static/

# Add documentation and configuration
Write-Host "🔄 Adding configuration files..." -ForegroundColor Cyan
git add "*.sh"
git add "*.yaml"
git add "*.yml"
git add "*.bat"

Write-Host ""
Write-Host "📊 Checking what will be committed..." -ForegroundColor Yellow
git status

Write-Host ""
Write-Host "💡 Next steps:" -ForegroundColor Green
Write-Host "   1. Review the files above with 'git status'" -ForegroundColor White
Write-Host "   2. Commit with: git commit -m `"Add Django project files, templates, and static files`"" -ForegroundColor White
Write-Host "   3. Add remote: git remote add origin YOUR_GITHUB_URL" -ForegroundColor White
Write-Host "   4. Push: git push -u origin main" -ForegroundColor White

Write-Host ""
Write-Host "⚠️  IMPORTANT NOTES:" -ForegroundColor Yellow
Write-Host "   - staticfiles/ is ignored (it is generated by collectstatic)" -ForegroundColor White
Write-Host "   - db.sqlite3 is ignored (database file should not be in git)" -ForegroundColor White
Write-Host "   - .env files are ignored (contains sensitive data)" -ForegroundColor White
Write-Host "   - templates/ and static/ WILL be included (source files)" -ForegroundColor White

Write-Host ""
Write-Host "Press any key to continue..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")