@echo off
REM Git Setup Script for Django Project
REM This script helps add templates, static files, and other important files to git

echo 🚀 Django Project Git Setup
echo ================================

echo.
echo 📁 Checking directories...
if exist "templates\" (
    echo ✅ templates/ directory found
) else (
    echo ❌ templates/ directory missing!
)

if exist "static\" (
    echo ✅ static/ directory found
) else (
    echo ❌ static/ directory missing!
)

if exist "staticfiles\" (
    echo ⚠️  staticfiles/ directory exists (will be ignored - it's generated)
) else (
    echo ℹ️  staticfiles/ directory not found (normal - it's generated)
)

echo.
echo 📋 Git operations...

REM Initialize git if not already done
if not exist ".git\" (
    echo 🔄 Initializing git repository...
    git init
) else (
    echo ✅ Git repository already initialized
)

REM Add .gitignore first
echo 🔄 Adding .gitignore...
git add .gitignore

REM Add all Django project files
echo 🔄 Adding Django project files...
git add manage.py
git add requirements.txt
git add runtime.txt
git add *.md
git add *.py

REM Add app directories
echo 🔄 Adding Django apps...
git add accounts/
git add chat/
git add genai_project/

REM Add templates and static files (source, not generated)
echo 🔄 Adding templates...
git add templates/

echo 🔄 Adding static source files...
git add static/

REM Add documentation and configuration
git add *.sh
git add *.yaml
git add *.yml

echo.
echo 📊 Checking what will be committed...
git status

echo.
echo 💡 Next steps:
echo    1. Review the files above with 'git status'
echo    2. Commit with: git commit -m "Add Django project files, templates, and static files"
echo    3. Add remote: git remote add origin YOUR_GITHUB_URL
echo    4. Push: git push -u origin main

echo.
echo ⚠️  IMPORTANT NOTES:
echo    - staticfiles/ is ignored (it's generated by collectstatic)
echo    - db.sqlite3 is ignored (database file shouldn't be in git)
echo    - .env files are ignored (contains sensitive data)
echo    - templates/ and static/ WILL be included (source files)

pause