# Generated by Django 4.2.16 on 2025-10-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversationstats_conversation_message_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fas fa-seedling", "Seedling (Getting Started)"),
                            ("fas fa-network-wired", "Network (Network Security)"),
                            ("fas fa-globe", "Globe (Web Security)"),
                            ("fas fa-bug", "Bug (Bug Bounty)"),
                            ("fas fa-search", "Search (Digital Forensics)"),
                            ("fas fa-shield-alt", "Shield (Advanced Security)"),
                            ("fas fa-laptop-code", "Laptop Code"),
                            ("fas fa-lock", "Lock"),
                            ("fas fa-key", "Key"),
                            ("fas fa-eye", "Eye"),
                        ],
                        default="fas fa-seedling",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LearningVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "youtube_id",
                    models.CharField(
                        help_text="YouTube video ID (e.g., 'ePD7cLWkt-E')",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="chat.learningmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("module", "order")},
            },
        ),
    ]
